language: python
python:
  - "3.6"

services: postgresql

cache: pip

env:
  global:
    - DJANGO_SETTINGS_MODULE=FreeTimeLance.test_settings
  matrix:
    - SAUCE_BROWSER="internet explorer" SAUCE_PLATFORM="Windows 10"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Windows 10"
    - SAUCE_BROWSER="chrome" SAUCE_PLATFORM="Linux"



install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install python-coveralls
  - pip install pylama
  - pip install flaky


script:
  - python manage.py makemigrations project
  - python manage.py migrate
  - py.test  --pylama --splinter-webdriver='remote' --force-flaky --max-run=3 --cov-config .coveragerc --cov=project --cov=FreeTimeLance --splinter-make-screenshot-on-failure=false

addons:
  sauce_connect: true

after_success:
  - coveralls
