# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0003_auto_20151126_1523'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('remarks', models.TextField(verbose_name='Remarks for the done work')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of the customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvitation',
            fields=[
                ('invitation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invitations.Invitation')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Customer')),
            ],
            bases=('invitations.invitation',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of the project')),
                ('description', models.TextField(verbose_name='Description of the target of the project')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('death_line', models.DateField(verbose_name='Death line')),
                ('workload', models.DurationField(verbose_name='Submitted number of working hours')),
                ('repository', models.URLField(verbose_name='Url of the repository')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Customer')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
