# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hamster_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Id of hamster activity'),
        ),
    ]
