# Generated by Django 2.0 on 2018-04-26 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('project', '0001_squashed_0003_auto_20161213_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of the project')),
                ('description', models.TextField(verbose_name='Description of the target of the project')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BaseProject'),
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('baseproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.BaseProject')),
                ('weekly_workload', models.DurationField(verbose_name='Normal number of weekly working hours')),
                ('vacation_days', models.IntegerField(verbose_name='Number of vacation days per year')),
            ],
            bases=('project.baseproject',),
        ),
        migrations.CreateModel(
            name='FreelanceProject',
            fields=[
                ('baseproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.BaseProject')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('death_line', models.DateField(verbose_name='Death line')),
                ('workload', models.DurationField(verbose_name='Submitted number of working hours')),
                ('repository', models.URLField(verbose_name='Url of the repository')),
            ],
            bases=('project.baseproject',),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='baseproject',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Customer'),
        ),
        migrations.AddField(
            model_name='baseproject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
