# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_activity_hamster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='remarks',
            field=models.TextField(null=True, verbose_name='Remarks for the done work'),
        ),
    ]
