# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('work', models.IntegerField(blank=True, null=True)),
                ('activity_order', models.IntegerField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
                ('search_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('color_code', models.TextField(blank=True, null=True)),
                ('category_order', models.IntegerField(blank=True, null=True)),
                ('search_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TextField(blank=True, null=True)),
                ('end_time', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'facts',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('autocomplete', models.NullBooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='FactTags',
            fields=[
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hamster_import.Facts')),
            ],
            options={
                'managed': False,
                'db_table': 'fact_tags',
            },
        ),
    ]
